{
  "build": {
    "publish": ".",
    "ignore": "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."
  },
  "redirects": [
    {
      "from": "/",
      "to": "/login.html",
      "status": 302,
      "force": false
    },
    {
      "from": "/index.html",
      "to": "/login.html", 
      "status": 302,
      "force": false
    }
  ],
  "headers": [
    {
      "for": "/*",
      "values": {
        "Cache-Control": "public, max-age=0, must-revalidate",
        "X-Frame-Options": "DENY",
        "X-Content-Type-Options": "nosniff"
      }
    },
    {
      "for": "*.js",
      "values": {
        "Cache-Control": "public, max-age=31536000, immutable"
      }
    },
    {
      "for": "*.css",
      "values": {
        "Cache-Control": "public, max-age=31536000, immutable"
      }
    }
  ]
}
